# Configuration file for model parameters and runs

# Basic model parameters options
basic_pars_options:
  lag:
    - lag
    - k0
    - theta
  intercept:
    - k0
    - B0
    - theta
  intercept_age_multiplicative:
    - k0
    - B0
    - theta
    - age

# Data parameter options
data_pars_options:
  - land_use_landscape_only
  - all

# Biomes to analyze
biomes: [1]

# Computational settings
ncores: 4
n_samples: 15000

# Parameter categories
climatic_pars:
  - srad
  - soil
  - temp
  - vpd
  - aet
  - def
  - pdsi
  - pr

land_use:
  - lu
  - fallow
  - num_fires

landscape:
  - dist
  - sur_cover
  - nearest_mature_biomass

categorical:
  - ecoreg
  - topography

# Parameter constraints
conditions:
  - 'pars["theta"] > 10'
  - 'pars["theta"] < 0'
  - 'pars["k0"] < 0'